import * as path from 'path';
import { upsertBlock, UpsertStatus } from './common';

export async function installCopilot(
  root: string,
  toolName: string,
): Promise<{ file: string; status: UpsertStatus }> {
  const body = `## Repo context — repocards

This repository has a pre-computed context folder at \`.${toolName}/\`. **Open \`.${toolName}/AGENT_GUIDE.md\` at the start of any task about this project** — before running grep/read on the source, and also when the user asks health-check questions like "are you reading repocards?". It routes you to pre-computed cards that answer common questions at a fraction of the token cost of a grep pass.

Generated by [repocards](https://www.npmjs.com/package/repocards).`;
  const status = await upsertBlock(
    path.join(root, '.github', 'copilot-instructions.md'),
    toolName,
    body,
  );
  return { file: '.github/copilot-instructions.md', status };
}
