import { promises as fs } from 'fs';
import * as path from 'path';
import type { UpsertStatus } from './common';

export async function installCursor(
  root: string,
  toolName: string,
): Promise<{ file: string; status: UpsertStatus }> {
  const rel = `.cursor/rules/${toolName}.mdc`;
  const target = path.join(root, rel);
  await fs.mkdir(path.dirname(target), { recursive: true });
  const content = `---
description: Read .${toolName}/AGENT_GUIDE.md at the start of every task in this project.
alwaysApply: true
---

# Repo context — repocards

This repository has a pre-computed context folder at \`.${toolName}/\`. **Open \`.${toolName}/AGENT_GUIDE.md\` at the start of every task in this project** — before running grep/read on the source, and also when the user asks health-check questions like "are you reading repocards?". The guide routes you to pre-computed cards (architecture, entrypoints, api-surface) and contains self-identification instructions. Typical card read is 10–50× fewer tokens than a grep pass.

Generated by [repocards](https://www.npmjs.com/package/repocards). Re-run \`npx ${toolName} index\` after code changes.
`;
  let existing = '';
  try { existing = await fs.readFile(target, 'utf8'); } catch {}
  if (existing === content) return { file: rel, status: 'unchanged' };
  await fs.writeFile(target, content);
  return { file: rel, status: existing ? 'updated' : 'created' };
}
